In [50]:
import numpy as np
import pandas as pd
import seaborn as sns

In [51]:
df=sns.load_dataset("titanic")
df.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [52]:
df=df[['survived','sex','class','alone','alive']]
df.head()

survived     sex  class  alone alive
0         0    male  Third  False    no
1         1  female  First  False   yes
2         1  female  Third   True   yes
3         1  female  First  False   yes
4         0    male  Third   True    no

In [53]:
df.isnull().sum()

survived    0
sex         0
class       0
alone       0
alive       0
dtype: int64

In [54]:
df['sex']=np.where(df['sex']=='male',1,0)
df

survived  sex   class  alone alive
0           0    1   Third  False    no
1           1    0   First  False   yes
2           1    0   Third   True   yes
3           1    0   First  False   yes
4           0    1   Third   True    no
..        ...  ...     ...    ...   ...
886         0    1  Second   True    no
887         1    0   First   True   yes
888         0    0   Third  False    no
889         1    1   First   True   yes
890         0    1   Third   True    no

[891 rows x 5 columns]

In [55]:
from sklearn.preprocessing import LabelEncoder
label=LabelEncoder()
c=label.fit_transform(df['class'])
c

array([2, 0, 2, 0, 2, 2, 0, 2, 2, 1, 2, 0, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1,
       2, 0, 2, 2, 2, 0, 2, 2, 0, 0, 2, 1, 0, 0, 2, 2, 2, 2, 2, 1, 2, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 0, 1, 0, 0, 1, 2, 1, 2, 2, 0, 0, 2, 0, 2,
       1, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 1, 2, 2, 2,
       0, 2, 2, 2, 0, 2, 2, 2, 0, 0, 1, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       0, 2, 2, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 1, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 1, 1, 1, 0, 0, 2, 0, 2, 2, 2, 2, 1, 1, 2, 2, 1, 1, 1, 0, 2, 2,
       2, 0, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 2, 0, 2,
       2, 0, 1, 2, 2, 1, 2, 1, 2, 0, 2, 0, 2, 2, 1, 1, 2, 1, 0, 0, 2, 2,
       2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 1, 2, 1, 2, 0, 2, 1, 0, 1,
       2, 1, 2, 2, 0, 2, 1, 2, 1, 2, 0, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2,
       1, 2, 2, 0, 2, 1, 0, 1, 2, 2, 0, 2, 2, 2, 0, 0, 0, 1, 2, 2, 0, 0,
       2, 1, 2, 2, 0, 0, 0, 2, 1, 0, 2, 0, 2, 1, 2, 2, 2, 2, 2, 2, 0, 2,
       2, 2, 1, 2, 0, 0, 1, 2, 2, 0, 2, 0, 0, 0, 2,

In [56]:
df['class']=c

In [57]:
df.head()

survived  sex  class  alone alive
0         0    1      2  False    no
1         1    0      0  False   yes
2         1    0      2   True   yes
3         1    0      0  False   yes
4         0    1      2   True    no

In [58]:
df['class'].unique()

array([2, 0, 1])

In [59]:
df['alone'].unique()

array([False,  True])

In [60]:
alone=label.fit_transform(df['alone'])
df['alone']=alone

In [61]:
df['alone'].unique()

array([0, 1])

In [62]:
df.drop('alive',axis=1,inplace=True)

In [63]:
df.head()

survived  sex  class  alone
0         0    1      2      0
1         1    0      0      0
2         1    0      2      1
3         1    0      0      0
4         0    1      2      1

In [64]:
X=df.drop('survived',axis=1)
Y=df['survived']

In [65]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

In [67]:
##chisquare-test
##chi-square return 2 values F-score and p-values
from sklearn.feature_selection import chi2
f_p_values=chi2(X_train,Y_train)
f_p_values

(array([83.99330276, 44.87368415, 11.89128429]),
 array([4.96453696e-20, 2.10163423e-11, 5.63972213e-04]))

In [68]:
p_values=pd.Series(f_p_values[1])
p_values.index=X_train.columns
p_values

sex      4.964537e-20
class    2.101634e-11
alone    5.639722e-04
dtype: float64

##Sex is the most important feature as higher the F-score and p-values more important is the feature